spring:
  application:
    name: blog-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blogv1.0?useUnicoce=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml